[workspace]
members = [
    "runtime-rust",
    "parseit-rust",
    "sdk-rust",
    "tests-executor-rust",
    "unicode-gen",
    "himecc-rust",
    # "langserv"
]

[patch.crates-io]
hime_redist = { path = "./runtime-rust" }
hime_sdk = { path = "./sdk-rust" }
