[package]
name = "hime_langserv"
version = "3.5.2"
authors = ["Laurent Wouters <lwouters@cenotelie.fr>"]
description = "Language server for Hime grammars"
documentation = "https://cenotelie.fr/projects/hime"
homepage = "https://cenotelie.fr/projects/hime"
repository = "https://github.com/cenotelie/hime"
readme = "README.md"
keywords = ["hime", "parser", "lr", "glr", "rnglr", "language-server"]
categories = ["algorithms", "parsing", "parser-implementations", "text-processing"]
license = "LGPL-3.0"
include = ["README.md", "Cargo.toml", "src/**/*.rs"]
edition = "2021"

[dependencies]
log = "0.4"
fern = "0.5"
clap = "2.33"
serde_json = "1.0"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
hime_redist = "3.5.2"
hime_sdk = "3.5.2"
tower-lsp = "0.14"

[badges]
maintenance = { status = "actively-developed" }
